spring:
  kafka:
    bootstrap-servers: j8c206.p.ssafy.io:9092
    consumer:
      max-poll-records: 100
      group-id: consumer-tlens
      auto-offset-reset: earliest
      enable-auto-commit: false
      client-id: consumer-tlens
    properties:
      session.timeout.ms: 45000
    listener:
      ack-mode: manual_immediate
      type: batch

server.port: 8095